const translations = {
  "fr": {
    "languageName": "Français",
    "kicker": "Sampans • Jura • France",
    "subtitle": "Un petit journal local, inspiré de Sampans en 1902.",
    "orderButton": "Commander un exemplaire",
    "posterButton": "Voir l’affiche",
    "languageIntro": "Choisir une langue",
    "posterTitle": "Affiche du lancement",
    "posterText": "Rendez-vous au marché des producteurs, rue Croix-d’Aval à Sampans, le samedi 27 juin 2026 à partir de 9h00.",
    "posterLarge": "Ouvrir l’affiche en grand format",
    "projectTitle": "Un journal venu du passé",
    "projectP1": "Le P’tiot Sampantais est une publication locale au format journal, imaginée comme si elle avait paru à Sampans au début du XXe siècle. On y retrouve des histoires du village, des archives, des portraits, des clins d’œil à la vie quotidienne et quelques nouvelles du monde.",
    "projectP2": "Ce projet est destiné aux habitants, aux familles, aux curieux, aux amoureux de l’histoire locale, mais aussi aux enfants.",
    "launchTitle": "Lancement",
    "launchDate": "Samedi 27 juin 2026",
    "launchPlace": "Marché des producteurs<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Jeux, danse médiévale, grand feu de la Saint-Jean, bal monté et restauration sur place.",
    "orderTitle": "Commander le journal",
    "orderIntro": "Une formule simple est proposée : 6 € par journal, dont 5 € pour le journal et 1 € de don pour l’École des Chiens Guides de Lyon Centre-Est, à Misérieux.",
    "onsiteTitle": "Sur place",
    "onsiteText": "Journal compris, avec 1 € reversé à l’association.",
    "franceShippingTitle": "Envoi en France",
    "franceShippingText": "Journal, don, enveloppe et affranchissement en Lettre suivie compris.",
    "worldShippingTitle": "Europe et reste du monde",
    "worldShippingText": "Journal, don, enveloppe et affranchissement international compris.",
    "donTitle": "Dons et frais postaux",
    "donP1": "Comme les frais postaux sont arrondis, il devrait rester un petit supplément d’environ 1 € par envoi. Ce supplément éventuel pourrait lui aussi être reversé à l’École des Chiens Guides.",
    "donP2": "L’idée est donc simple : 1 € par journal vendu est reversé à l’association, ainsi que le petit supplément éventuel lié aux envois postaux.",
    "postalFormTitle": "Formulaire pour l’envoi par la poste",
    "postalFormIntro": "Remplissez ce formulaire pour envoyer automatiquement votre demande à contact@sampans.org. Vous serez ensuite redirigé vers la page de paiement.",
    "fullNameLabel": "Nom et prénom *",
    "emailLabel": "Adresse e-mail *",
    "postalAddressLabel": "Adresse postale complète *",
    "postalCodeLabel": "Code postal *",
    "cityLabel": "Ville *",
    "countryLabel": "Pays *",
    "copiesLabel": "Nombre d’exemplaires souhaités *",
    "shippingModeLabel": "Mode d’envoi choisi *",
    "chooseOption": "Choisir…",
    "shippingFranceOption": "France — 12 € par exemplaire",
    "shippingEuropeOption": "Europe — 18 € par exemplaire",
    "shippingWorldOption": "Reste du monde — 18 € par exemplaire",
    "phoneLabel": "Numéro de téléphone, facultatif",
    "paymentProofLabel": "Preuve ou confirmation de paiement, si paiement par virement *",
    "paymentProofPlaceholder": "Exemple : virement effectué le…, nom du titulaire, référence éventuelle. Si vous avez une capture d’écran, joignez-la ensuite à l’e-mail.",
    "messageLabel": "Message particulier, facultatif",
    "messagePlaceholder": "Exemple : à offrir, envoi à une autre personne, précision de livraison…",
    "formNote": "Les informations transmises servent uniquement à préparer l’envoi du journal par la poste. Elles ne seront pas utilisées à d’autres fins.",
    "formSubmitButton": "Envoyer la demande de commande",
    "paymentComing": "Après l’envoi du formulaire, vous serez dirigé vers la page de paiement.",
    "paymentButton": "Aller à la page de paiement",
    "aboutTitle": "À propos",
    "aboutP1": "Ce site est une initiative locale indépendante autour de la mémoire de Sampans. Il ne remplace pas les informations officielles de la commune.",
    "contact": "Contact :",
    "priceTitle": "Prix calculé",
    "priceHelp": "Le prix se calcule automatiquement avec les frais de paiement estimés.",
    "specialOrder": "Pour une commande spéciale, écrivez directement à"
  },
  "en": {
    "languageName": "English",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Order a copy",
    "posterButton": "See the poster",
    "languageIntro": "Choose a language",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Postal delivery form",
    "postalFormIntro": "Fill in this form to send your request automatically to contact@sampans.org. You will then be redirected to the payment page.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France — €12 per copy",
    "shippingEuropeOption": "Europe — €18 per copy",
    "shippingWorldOption": "Rest of the world — €18 per copy",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "The information sent is used only to prepare the postal delivery of the newspaper. It will not be used for any other purpose.",
    "formSubmitButton": "Send order request",
    "paymentComing": "After sending the form, you will be taken to the payment page.",
    "paymentButton": "Go to the payment page",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:",
    "priceTitle": "Calculated price",
    "priceHelp": "The price is calculated automatically with estimated payment fees.",
    "specialOrder": "For a special order, please write directly to"
  },
  "de": {
    "languageName": "Deutsch",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Ein Exemplar bestellen",
    "posterButton": "Plakat ansehen",
    "languageIntro": "Sprache wählen",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Formular für den Postversand",
    "postalFormIntro": "Füllen Sie dieses Formular aus, um Ihre Anfrage automatisch an contact@sampans.org zu senden. Danach werden Sie zur Zahlungsseite weitergeleitet.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France — €12 per copy",
    "shippingEuropeOption": "Europe — €18 per copy",
    "shippingWorldOption": "Rest of the world — €18 per copy",
    "phoneLabel": "Telefon, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Besondere Nachricht, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "Die übermittelten Informationen werden nur zur Vorbereitung des Postversands der Zeitung verwendet.",
    "formSubmitButton": "Send order request",
    "paymentComing": "Nach dem Absenden des Formulars werden Sie zur Zahlungsseite weitergeleitet.",
    "paymentButton": "Zur Zahlungsseite",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:",
    "priceTitle": "Calculated price",
    "priceHelp": "Der Preis wird automatisch mit geschätzten Zahlungsgebühren berechnet.",
    "specialOrder": "For a special order, please write directly to"
  },
  "sr": {
    "languageName": "Српски",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Наручити примерак",
    "posterButton": "Погледати плакат",
    "languageIntro": "Изаберите језик",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Образац за слање поштом",
    "postalFormIntro": "Попуните овај образац да бисте аутоматски послали захтев на contact@sampans.org. Затим ћете бити преусмерени на страницу за плаћање.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France — €12 per copy",
    "shippingEuropeOption": "Europe — €18 per copy",
    "shippingWorldOption": "Rest of the world — €18 per copy",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "Послати подаци користе се само за припрему поштанског слања новина.",
    "formSubmitButton": "Send order request",
    "paymentComing": "Након слања обрасца бићете преусмерени на страницу за плаћање.",
    "paymentButton": "Иди на страницу за плаћање",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:",
    "priceTitle": "Calculated price",
    "priceHelp": "Цена се аутоматски израчунава са процењеним трошковима плаћања.",
    "specialOrder": "For a special order, please write directly to"
  },
  "zh": {
    "languageName": "中文",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "订购一份",
    "posterButton": "查看海报",
    "languageIntro": "选择语言",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "邮寄表格",
    "postalFormIntro": "请填写此表格，将请求自动发送至 contact@sampans.org。随后您将被重定向到付款页面。",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France — €12 per copy",
    "shippingEuropeOption": "Europe — €18 per copy",
    "shippingWorldOption": "Rest of the world — €18 per copy",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "提交的信息仅用于准备报纸的邮寄，不会用于其他用途。",
    "formSubmitButton": "Send order request",
    "paymentComing": "提交表格后，您将进入付款页面。",
    "paymentButton": "前往付款页面",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:",
    "priceTitle": "Calculated price",
    "priceHelp": "价格会自动加入预计的付款手续费。",
    "specialOrder": "For a special order, please write directly to"
  },
  "ar": {
    "languageName": "العربية",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "طلب نسخة",
    "posterButton": "عرض الملصق",
    "languageIntro": "اختر اللغة",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "استمارة الإرسال بالبريد",
    "postalFormIntro": "املأ هذه الاستمارة لإرسال طلبك تلقائياً إلى contact@sampans.org. بعد ذلك سيتم تحويلك إلى صفحة الدفع.",
    "fullNameLabel": "الاسم واللقب *",
    "emailLabel": "البريد الإلكتروني *",
    "postalAddressLabel": "العنوان البريدي الكامل *",
    "postalCodeLabel": "الرمز البريدي *",
    "cityLabel": "المدينة *",
    "countryLabel": "البلد *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France — €12 per copy",
    "shippingEuropeOption": "Europe — €18 per copy",
    "shippingWorldOption": "Rest of the world — €18 per copy",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "تُستخدم المعلومات المرسلة فقط لتحضير إرسال الجريدة بالبريد، ولن تُستخدم لأي غرض آخر.",
    "formSubmitButton": "Send order request",
    "paymentComing": "بعد إرسال الاستمارة، سيتم تحويلك إلى صفحة الدفع.",
    "paymentButton": "الانتقال إلى صفحة الدفع",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:",
    "priceTitle": "Calculated price",
    "priceHelp": "يتم حساب السعر تلقائياً مع رسوم الدفع المقدّرة.",
    "specialOrder": "For a special order, please write directly to"
  },
  "ms": {
    "languageName": "Bahasa Melayu",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Pesan satu naskhah",
    "posterButton": "Lihat poster",
    "languageIntro": "Pilih bahasa",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Borang penghantaran pos",
    "postalFormIntro": "Isi borang ini untuk menghantar permintaan anda secara automatik kepada contact@sampans.org. Anda kemudian akan dibawa ke halaman pembayaran.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France — €12 per copy",
    "shippingEuropeOption": "Europe — €18 per copy",
    "shippingWorldOption": "Rest of the world — €18 per copy",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "Maklumat yang dihantar hanya digunakan untuk menyediakan penghantaran pos akhbar ini.",
    "formSubmitButton": "Send order request",
    "paymentComing": "Selepas menghantar borang, anda akan dibawa ke halaman pembayaran.",
    "paymentButton": "Pergi ke halaman pembayaran",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:",
    "priceTitle": "Calculated price",
    "priceHelp": "Harga dikira secara automatik dengan anggaran caj pembayaran.",
    "specialOrder": "For a special order, please write directly to"
  },
  "es": {
    "languageName": "Español",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Order a copy",
    "posterButton": "See the poster",
    "languageIntro": "Choose a language",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Postal delivery form",
    "postalFormIntro": "Rellene este formulario para enviar automáticamente su solicitud a contact@sampans.org. A continuación será redirigido a la página de pago.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France — €12 per copy",
    "shippingEuropeOption": "Europe — €18 per copy",
    "shippingWorldOption": "Rest of the world — €18 per copy",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "La información enviada se utiliza únicamente para preparar el envío postal del periódico. No se usará para otros fines.",
    "formSubmitButton": "Send order request",
    "paymentComing": "Después de enviar el formulario, accederá a la página de pago.",
    "paymentButton": "Ir a la página de pago",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:",
    "priceTitle": "Calculated price",
    "priceHelp": "El precio se calcula automáticamente con los gastos de pago estimados.",
    "specialOrder": "For a special order, please write directly to"
  },
  "pt": {
    "languageName": "Português",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Order a copy",
    "posterButton": "See the poster",
    "languageIntro": "Choose a language",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Postal delivery form",
    "postalFormIntro": "Preencha este formulário para enviar automaticamente o seu pedido para contact@sampans.org. Em seguida, será encaminhado para a página de pagamento.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France — €12 per copy",
    "shippingEuropeOption": "Europe — €18 per copy",
    "shippingWorldOption": "Rest of the world — €18 per copy",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "As informações enviadas são usadas apenas para preparar o envio postal do jornal. Não serão usadas para outros fins.",
    "formSubmitButton": "Send order request",
    "paymentComing": "Depois de enviar o formulário, será encaminhado para a página de pagamento.",
    "paymentButton": "Ir para a página de pagamento",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:",
    "priceTitle": "Calculated price",
    "priceHelp": "O preço é calculado automaticamente com as taxas de pagamento estimadas.",
    "specialOrder": "For a special order, please write directly to"
  },
  "ko": {
    "languageName": "한국어",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Order a copy",
    "posterButton": "See the poster",
    "languageIntro": "Choose a language",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Postal delivery form",
    "postalFormIntro": "이 양식을 작성하면 요청이 contact@sampans.org로 자동 전송됩니다. 이후 결제 페이지로 이동합니다.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France — €12 per copy",
    "shippingEuropeOption": "Europe — €18 per copy",
    "shippingWorldOption": "Rest of the world — €18 per copy",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "제출된 정보는 신문 우편 발송 준비에만 사용됩니다.",
    "formSubmitButton": "Send order request",
    "paymentComing": "양식을 보낸 후 결제 페이지로 이동합니다.",
    "paymentButton": "결제 페이지로 이동",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:",
    "priceTitle": "Calculated price",
    "priceHelp": "가격은 예상 결제 수수료를 포함해 자동 계산됩니다.",
    "specialOrder": "For a special order, please write directly to"
  },
  "ta": {
    "languageName": "தமிழ்",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Order a copy",
    "posterButton": "See the poster",
    "languageIntro": "Choose a language",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Postal delivery form",
    "postalFormIntro": "இந்தப் படிவத்தை நிரப்பினால், உங்கள் கோரிக்கை contact@sampans.org க்கு தானாக அனுப்பப்படும். அதன் பிறகு கட்டணப் பக்கத்துக்கு மாற்றப்படுவீர்கள்.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France — €12 per copy",
    "shippingEuropeOption": "Europe — €18 per copy",
    "shippingWorldOption": "Rest of the world — €18 per copy",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "அனுப்பப்படும் தகவல்கள் செய்தித்தாளை அஞ்சலில் அனுப்பத் தயாரிப்பதற்காக மட்டுமே பயன்படுத்தப்படும்.",
    "formSubmitButton": "Send order request",
    "paymentComing": "படிவத்தை அனுப்பிய பிறகு, நீங்கள் கட்டணப் பக்கத்துக்கு மாற்றப்படுவீர்கள்.",
    "paymentButton": "கட்டணப் பக்கத்துக்கு செல்ல",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:",
    "priceTitle": "Calculated price",
    "priceHelp": "கட்டணச் செலவுகள் மதிப்பீட்டுடன் விலை தானாகக் கணக்கிடப்படும்.",
    "specialOrder": "For a special order, please write directly to"
  }
};

function setLanguage(lang) {
  const data = translations[lang] || translations.fr;
  document.documentElement.lang = lang;
  document.documentElement.dir = (lang === "ar") ? "rtl" : "ltr";

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.getAttribute("data-i18n");
    if (data[key]) element.textContent = data[key];
  });

  document.querySelectorAll("[data-i18n-html]").forEach((element) => {
    const key = element.getAttribute("data-i18n-html");
    if (data[key]) element.innerHTML = data[key];
  });

  document.querySelectorAll("[data-i18n-placeholder]").forEach((element) => {
    const key = element.getAttribute("data-i18n-placeholder");
    if (data[key]) element.setAttribute("placeholder", data[key]);
  });

  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.classList.toggle("active", button.getAttribute("data-lang") === lang);
  });

  localStorage.setItem("sampansLanguage", lang);
}

function formatEuro(amount) {
  return amount.toFixed(2).replace(".", ",") + " €";
}

function updateCalculatedPrice() {
  const copiesInput = document.getElementById("copiesInput");
  const shippingMode = document.getElementById("shippingMode");
  const priceResult = document.getElementById("priceResult");
  const hiddenSubtotalPrice = document.getElementById("hiddenSubtotalPrice");
  const hiddenPaymentFees = document.getElementById("hiddenPaymentFees");
  const hiddenTotalPrice = document.getElementById("hiddenTotalPrice");

  if (!copiesInput || !shippingMode || !priceResult || !hiddenTotalPrice) return;

  let copies = parseInt(copiesInput.value || "1", 10);
  if (!Number.isFinite(copies) || copies < 1) copies = 1;
  copiesInput.value = copies;

  let unitPrice = 0;
  let label = shippingMode.value;

  if (shippingMode.value === "France") unitPrice = 12;
  if (shippingMode.value === "Europe") unitPrice = 18;
  if (shippingMode.value === "Reste du monde") unitPrice = 18;

  if (!unitPrice) {
    priceResult.textContent = "Choisissez le mode d’envoi.";
    if (hiddenSubtotalPrice) hiddenSubtotalPrice.value = "Non calculé";
    if (hiddenPaymentFees) hiddenPaymentFees.value = "Non calculé";
    hiddenTotalPrice.value = "Non calculé";
    return;
  }

  const subtotal = copies * unitPrice;

  // Frais estimés Mollie pour une carte bancaire particulier FR/EEE :
  // 0,20 € + 1,2 %. On calcule le total pour conserver le net souhaité.
  const feeFixed = 0.20;
  const feeRate = 0.012;
  const total = Math.ceil(((subtotal + feeFixed) / (1 - feeRate)) * 100) / 100;
  const fees = Math.max(0, total - subtotal);

  const copiesText = copies + " exemplaire" + (copies > 1 ? "s" : "");
  const subtotalText = formatEuro(subtotal);
  const feesText = formatEuro(fees);
  const totalText = formatEuro(total);

  priceResult.innerHTML = totalText + " — " + copiesText + " — " + label
    + "<br><span class=\"price-breakdown\">Dont " + subtotalText
    + " pour journal/envoi + " + feesText
    + " de frais de paiement estimés.</span>";

  if (hiddenSubtotalPrice) hiddenSubtotalPrice.value = subtotalText;
  if (hiddenPaymentFees) hiddenPaymentFees.value = feesText;
  hiddenTotalPrice.value = totalText + " — " + copiesText + " — " + label;
}

document.addEventListener("DOMContentLoaded", () => {
  const savedLanguage = localStorage.getItem("sampansLanguage");
  const browserLanguage = (navigator.language || "fr").slice(0, 2);
  const initialLanguage = savedLanguage || (translations[browserLanguage] ? browserLanguage : "fr");

  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.addEventListener("click", () => setLanguage(button.getAttribute("data-lang")));
  });

  const copiesInput = document.getElementById("copiesInput");
  const shippingMode = document.getElementById("shippingMode");
  const form = document.getElementById("postalOrderForm");

  if (copiesInput) copiesInput.addEventListener("input", updateCalculatedPrice);
  if (shippingMode) shippingMode.addEventListener("change", updateCalculatedPrice);
  if (form) form.addEventListener("submit", updateCalculatedPrice);

  setLanguage(initialLanguage);
  updateCalculatedPrice();
});
