const translations = {
  "fr": {
    "languageName": "Français",
    "kicker": "Sampans • Jura • France",
    "subtitle": "Un petit journal local, inspiré de Sampans en 1902.",
    "orderButton": "Commander un exemplaire",
    "posterButton": "Voir l’affiche",
    "languageIntro": "Choisir une langue",
    "posterTitle": "Affiche du lancement",
    "posterText": "Rendez-vous au marché des producteurs, rue Croix-d’Aval à Sampans, le samedi 27 juin 2026 à partir de 9h00.",
    "posterLarge": "Ouvrir l’affiche en grand format",
    "projectTitle": "Un journal venu du passé",
    "projectP1": "Le P’tiot Sampantais est une publication locale au format journal, imaginée comme si elle avait paru à Sampans au début du XXe siècle. On y retrouve des histoires du village, des archives, des portraits, des clins d’œil à la vie quotidienne et quelques nouvelles du monde.",
    "projectP2": "Ce projet est destiné aux habitants, aux familles, aux curieux, aux amoureux de l’histoire locale, mais aussi aux enfants.",
    "launchTitle": "Lancement",
    "launchDate": "Samedi 27 juin 2026",
    "launchPlace": "Marché des producteurs<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Jeux, danse médiévale, grand feu de la Saint-Jean, bal monté et restauration sur place.",
    "orderTitle": "Commander le journal",
    "orderIntro": "Une formule simple est proposée : 6 € par journal, dont 5 € pour le journal et 1 € de don pour l’École des Chiens Guides de Lyon Centre-Est, à Misérieux.",
    "onsiteTitle": "Sur place",
    "onsiteText": "Journal compris, avec 1 € reversé à l’association.",
    "franceShippingTitle": "Envoi en France",
    "franceShippingText": "Journal, don, enveloppe et affranchissement en Lettre suivie compris.",
    "worldShippingTitle": "Europe et reste du monde",
    "worldShippingText": "Journal, don, enveloppe et affranchissement international compris.",
    "donTitle": "Dons et frais postaux",
    "donP1": "Comme les frais postaux sont arrondis, il devrait rester un petit supplément d’environ 1 € par envoi. Ce supplément éventuel pourrait lui aussi être reversé à l’École des Chiens Guides.",
    "donP2": "L’idée est donc simple : 1 € par journal vendu est reversé à l’association, ainsi que le petit supplément éventuel lié aux envois postaux.",
    "postalFormTitle": "Formulaire pour l’envoi par la poste",
    "postalFormIntro": "Remplissez ce formulaire pour préparer votre demande d’envoi. Le bouton ouvrira votre logiciel de messagerie avec les informations prêtes à envoyer à contact@sampans.org.",
    "fullNameLabel": "Nom et prénom *",
    "emailLabel": "Adresse e-mail *",
    "postalAddressLabel": "Adresse postale complète *",
    "postalCodeLabel": "Code postal *",
    "cityLabel": "Ville *",
    "countryLabel": "Pays *",
    "copiesLabel": "Nombre d’exemplaires souhaités *",
    "shippingModeLabel": "Mode d’envoi choisi *",
    "chooseOption": "Choisir…",
    "shippingFranceOption": "France",
    "shippingEuropeOption": "Europe",
    "shippingWorldOption": "Reste du monde",
    "phoneLabel": "Numéro de téléphone, facultatif",
    "paymentProofLabel": "Preuve ou confirmation de paiement, si paiement par virement *",
    "paymentProofPlaceholder": "Exemple : virement effectué le…, nom du titulaire, référence éventuelle. Si vous avez une capture d’écran, joignez-la ensuite à l’e-mail.",
    "messageLabel": "Message particulier, facultatif",
    "messagePlaceholder": "Exemple : à offrir, envoi à une autre personne, précision de livraison…",
    "formNote": "Aucun paiement n’est effectué par ce formulaire. Il sert uniquement à envoyer les informations nécessaires à la préparation de l’envoi postal.",
    "formSubmitButton": "Préparer l’e-mail de commande",
    "paymentComing": "Le lien de paiement sera ajouté ici dès qu’il sera validé.",
    "paymentButton": "Lien de paiement à venir",
    "aboutTitle": "À propos",
    "aboutP1": "Ce site est une initiative locale indépendante autour de la mémoire de Sampans. Il ne remplace pas les informations officielles de la commune.",
    "contact": "Contact :"
  },
  "en": {
    "languageName": "English",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Order a copy",
    "posterButton": "See the poster",
    "languageIntro": "Choose a language",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Postal delivery form",
    "postalFormIntro": "Fill in this form to prepare your postal order request. The button will open your email app with the details ready to send to contact@sampans.org.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France",
    "shippingEuropeOption": "Europe",
    "shippingWorldOption": "Rest of the world",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "No payment is made through this form. It only sends the details needed to prepare the postal delivery.",
    "formSubmitButton": "Prepare the order email",
    "paymentComing": "The payment link will be added here as soon as it is validated.",
    "paymentButton": "Payment link coming soon",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:"
  },
  "de": {
    "languageName": "Deutsch",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Ein Exemplar bestellen",
    "posterButton": "Plakat ansehen",
    "languageIntro": "Sprache wählen",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Formular für den Postversand",
    "postalFormIntro": "Fill in this form to prepare your postal order request. The button will open your email app with the details ready to send to contact@sampans.org.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France",
    "shippingEuropeOption": "Europe",
    "shippingWorldOption": "Rest of the world",
    "phoneLabel": "Telefon, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Besondere Nachricht, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "No payment is made through this form. It only sends the details needed to prepare the postal delivery.",
    "formSubmitButton": "Bestell-E-Mail vorbereiten",
    "paymentComing": "The payment link will be added here as soon as it is validated.",
    "paymentButton": "Payment link coming soon",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:"
  },
  "sr": {
    "languageName": "Српски",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Наручити примерак",
    "posterButton": "Погледати плакат",
    "languageIntro": "Изаберите језик",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Образац за слање поштом",
    "postalFormIntro": "Fill in this form to prepare your postal order request. The button will open your email app with the details ready to send to contact@sampans.org.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France",
    "shippingEuropeOption": "Europe",
    "shippingWorldOption": "Rest of the world",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "No payment is made through this form. It only sends the details needed to prepare the postal delivery.",
    "formSubmitButton": "Припремити е-поруку за наруџбину",
    "paymentComing": "The payment link will be added here as soon as it is validated.",
    "paymentButton": "Payment link coming soon",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:"
  },
  "zh": {
    "languageName": "中文",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "订购一份",
    "posterButton": "查看海报",
    "languageIntro": "选择语言",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "邮寄表格",
    "postalFormIntro": "Fill in this form to prepare your postal order request. The button will open your email app with the details ready to send to contact@sampans.org.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France",
    "shippingEuropeOption": "Europe",
    "shippingWorldOption": "Rest of the world",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "No payment is made through this form. It only sends the details needed to prepare the postal delivery.",
    "formSubmitButton": "准备订单邮件",
    "paymentComing": "The payment link will be added here as soon as it is validated.",
    "paymentButton": "Payment link coming soon",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:"
  },
  "ar": {
    "languageName": "العربية",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "طلب نسخة",
    "posterButton": "عرض الملصق",
    "languageIntro": "اختر اللغة",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "استمارة الإرسال بالبريد",
    "postalFormIntro": "Fill in this form to prepare your postal order request. The button will open your email app with the details ready to send to contact@sampans.org.",
    "fullNameLabel": "الاسم واللقب *",
    "emailLabel": "البريد الإلكتروني *",
    "postalAddressLabel": "العنوان البريدي الكامل *",
    "postalCodeLabel": "الرمز البريدي *",
    "cityLabel": "المدينة *",
    "countryLabel": "البلد *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France",
    "shippingEuropeOption": "Europe",
    "shippingWorldOption": "Rest of the world",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "No payment is made through this form. It only sends the details needed to prepare the postal delivery.",
    "formSubmitButton": "تحضير رسالة الطلب",
    "paymentComing": "The payment link will be added here as soon as it is validated.",
    "paymentButton": "Payment link coming soon",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:"
  },
  "ms": {
    "languageName": "Bahasa Melayu",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Pesan satu naskhah",
    "posterButton": "Lihat poster",
    "languageIntro": "Pilih bahasa",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Borang penghantaran pos",
    "postalFormIntro": "Fill in this form to prepare your postal order request. The button will open your email app with the details ready to send to contact@sampans.org.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France",
    "shippingEuropeOption": "Europe",
    "shippingWorldOption": "Rest of the world",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "No payment is made through this form. It only sends the details needed to prepare the postal delivery.",
    "formSubmitButton": "Sediakan e-mel pesanan",
    "paymentComing": "The payment link will be added here as soon as it is validated.",
    "paymentButton": "Payment link coming soon",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:"
  },
  "es": {
    "languageName": "Español",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Order a copy",
    "posterButton": "See the poster",
    "languageIntro": "Choose a language",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Postal delivery form",
    "postalFormIntro": "Fill in this form to prepare your postal order request. The button will open your email app with the details ready to send to contact@sampans.org.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France",
    "shippingEuropeOption": "Europe",
    "shippingWorldOption": "Rest of the world",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "No payment is made through this form. It only sends the details needed to prepare the postal delivery.",
    "formSubmitButton": "Prepare the order email",
    "paymentComing": "The payment link will be added here as soon as it is validated.",
    "paymentButton": "Payment link coming soon",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:"
  },
  "pt": {
    "languageName": "Português",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Order a copy",
    "posterButton": "See the poster",
    "languageIntro": "Choose a language",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Postal delivery form",
    "postalFormIntro": "Fill in this form to prepare your postal order request. The button will open your email app with the details ready to send to contact@sampans.org.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France",
    "shippingEuropeOption": "Europe",
    "shippingWorldOption": "Rest of the world",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "No payment is made through this form. It only sends the details needed to prepare the postal delivery.",
    "formSubmitButton": "Prepare the order email",
    "paymentComing": "The payment link will be added here as soon as it is validated.",
    "paymentButton": "Payment link coming soon",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:"
  },
  "ko": {
    "languageName": "한국어",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Order a copy",
    "posterButton": "See the poster",
    "languageIntro": "Choose a language",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Postal delivery form",
    "postalFormIntro": "Fill in this form to prepare your postal order request. The button will open your email app with the details ready to send to contact@sampans.org.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France",
    "shippingEuropeOption": "Europe",
    "shippingWorldOption": "Rest of the world",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "No payment is made through this form. It only sends the details needed to prepare the postal delivery.",
    "formSubmitButton": "Prepare the order email",
    "paymentComing": "The payment link will be added here as soon as it is validated.",
    "paymentButton": "Payment link coming soon",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:"
  },
  "ta": {
    "languageName": "தமிழ்",
    "kicker": "Sampans • Jura • France",
    "subtitle": "A small local newspaper inspired by Sampans in 1902.",
    "orderButton": "Order a copy",
    "posterButton": "See the poster",
    "languageIntro": "Choose a language",
    "posterTitle": "Launch poster",
    "posterText": "Join us at the producers’ market, rue Croix-d’Aval in Sampans, on Saturday 27 June 2026 from 9:00 a.m.",
    "posterLarge": "Open the poster in large format",
    "projectTitle": "A newspaper from the past",
    "projectP1": "Le P’tiot Sampantais is a local newspaper-style publication, imagined as if it had appeared in Sampans at the beginning of the twentieth century. It includes village stories, archives, portraits, glimpses of everyday life and a few items of world news.",
    "projectP2": "The project is for residents, families, curious readers, lovers of local history, and also children.",
    "launchTitle": "Launch",
    "launchDate": "Saturday 27 June 2026",
    "launchPlace": "Producers’ market<br>Rue Croix-d’Aval, Sampans",
    "launchProgramme": "Games, medieval dance, Saint John’s bonfire, dance with accordion music and food on site.",
    "orderTitle": "Order the newspaper",
    "orderIntro": "A simple formula is proposed: €6 per copy, including €5 for the newspaper and a €1 donation to the École des Chiens Guides de Lyon Centre-Est in Misérieux.",
    "onsiteTitle": "At the event",
    "onsiteText": "One newspaper included, with €1 donated to the association.",
    "franceShippingTitle": "Delivery in France",
    "franceShippingText": "Includes the newspaper, donation, envelope and tracked letter postage.",
    "worldShippingTitle": "Europe and the rest of the world",
    "worldShippingText": "Includes the newspaper, donation, envelope and international postage.",
    "donTitle": "Donations and postage",
    "donP1": "As postal costs are rounded, there should be a small surplus of about €1 per postal order. This possible surplus could also be donated to the guide dog school.",
    "donP2": "The idea is simple: €1 from each newspaper sold is donated to the association, along with any small surplus linked to postal orders.",
    "postalFormTitle": "Postal delivery form",
    "postalFormIntro": "Fill in this form to prepare your postal order request. The button will open your email app with the details ready to send to contact@sampans.org.",
    "fullNameLabel": "Full name *",
    "emailLabel": "Email address *",
    "postalAddressLabel": "Full postal address *",
    "postalCodeLabel": "Postcode / ZIP code *",
    "cityLabel": "Town / City *",
    "countryLabel": "Country *",
    "copiesLabel": "Number of copies requested *",
    "shippingModeLabel": "Chosen shipping method *",
    "chooseOption": "Choose…",
    "shippingFranceOption": "France",
    "shippingEuropeOption": "Europe",
    "shippingWorldOption": "Rest of the world",
    "phoneLabel": "Phone number, optional",
    "paymentProofLabel": "Payment proof or confirmation, if paying by bank transfer *",
    "paymentProofPlaceholder": "Example: transfer made on…, account holder name, reference if any. If you have a screenshot, attach it to the email afterwards.",
    "messageLabel": "Special message, optional",
    "messagePlaceholder": "Example: gift, sent to another person, delivery note…",
    "formNote": "No payment is made through this form. It only sends the details needed to prepare the postal delivery.",
    "formSubmitButton": "Prepare the order email",
    "paymentComing": "The payment link will be added here as soon as it is validated.",
    "paymentButton": "Payment link coming soon",
    "aboutTitle": "About",
    "aboutP1": "This site is an independent local initiative dedicated to the memory of Sampans. It does not replace official information from the municipality.",
    "contact": "Contact:"
  }
};

function setLanguage(lang) {
  const data = translations[lang] || translations.fr;
  document.documentElement.lang = lang;
  document.documentElement.dir = (lang === "ar") ? "rtl" : "ltr";

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.getAttribute("data-i18n");
    if (data[key]) element.textContent = data[key];
  });

  document.querySelectorAll("[data-i18n-html]").forEach((element) => {
    const key = element.getAttribute("data-i18n-html");
    if (data[key]) element.innerHTML = data[key];
  });

  document.querySelectorAll("[data-i18n-placeholder]").forEach((element) => {
    const key = element.getAttribute("data-i18n-placeholder");
    if (data[key]) element.setAttribute("placeholder", data[key]);
  });

  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.classList.toggle("active", button.getAttribute("data-lang") === lang);
  });

  localStorage.setItem("sampansLanguage", lang);
}

function valueOf(form, name) {
  const field = form.elements[name];
  return field ? String(field.value || "").trim() : "";
}

function preparePostalOrderEmail(event) {
  event.preventDefault();

  const form = event.currentTarget;
  if (!form.reportValidity()) return;

  const subject = "Commande postale — Le P’tiot Sampantais";

  const body = [
    "Bonjour,",
    "",
    "Je souhaite commander Le P’tiot Sampantais par la poste.",
    "",
    "Nom et prénom : " + valueOf(form, "nom_prenom"),
    "Adresse e-mail : " + valueOf(form, "email"),
    "",
    "Adresse postale complète :",
    valueOf(form, "adresse"),
    "",
    "Code postal : " + valueOf(form, "code_postal"),
    "Ville : " + valueOf(form, "ville"),
    "Pays : " + valueOf(form, "pays"),
    "",
    "Nombre d’exemplaires souhaités : " + valueOf(form, "exemplaires"),
    "Mode d’envoi choisi : " + valueOf(form, "mode_envoi"),
    "",
    "Preuve ou confirmation de paiement, si paiement par virement :",
    valueOf(form, "preuve_paiement"),
    "",
    "Téléphone : " + (valueOf(form, "telephone") || "Non renseigné"),
    "",
    "Message particulier :",
    valueOf(form, "message") || "Aucun",
    "",
    "Merci."
  ].join("\n");

  window.location.href = "mailto:contact@sampans.org"
    + "?subject=" + encodeURIComponent(subject)
    + "&body=" + encodeURIComponent(body);
}

document.addEventListener("DOMContentLoaded", () => {
  const savedLanguage = localStorage.getItem("sampansLanguage");
  const browserLanguage = (navigator.language || "fr").slice(0, 2);
  const initialLanguage = savedLanguage || (translations[browserLanguage] ? browserLanguage : "fr");

  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.addEventListener("click", () => setLanguage(button.getAttribute("data-lang")));
  });

  const postalForm = document.getElementById("postalOrderForm");
  if (postalForm) {
    postalForm.addEventListener("submit", preparePostalOrderEmail);
  }

  setLanguage(initialLanguage);
});
